### PR TITLE
Bump version of rpgffi

### PR DESCRIPTION
**Pull request by posix4e**
It's be good if you try on OSX @solidsnack

### CODE REVIEW

**Comment by jmealo** [comment]
In order to run `cargo build` I had to manually make this edit.

**Comment by jmealo** [comment]
@posix4e: The build isn't working on OSX for me with and without the change. on Linux `cargo buiild` fails parsing the .toml file. On OSX I get this:

```
jmealo$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading rpgffi v0.1.1
   Compiling rpgffi v0.1.1
   Compiling jsoncdc v0.0.9 (file:///Users/jmealo/Repos/jsoncdc)
error: linking with `cc` failed: exit code: 1
note: "cc" "-m64" "-L" "/usr/local/Cellar/rust/1.9.0/lib/rustlib/x86_64-apple-darwin/lib" "/Users/jmealo/Repos/jsoncdc/target/debug/jsoncdc.0.o" "-o" "/Users/jmealo/Repos/jsoncdc/target/debug/libjsoncdc.dylib" "/Users/jmealo/Repos/jsoncdc/target/debug/jsoncdc.metadata.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/jmealo/Repos/jsoncdc/target/debug" "-L" "/Users/jmealo/Repos/jsoncdc/target/debug/deps" "-L" "/Users/jmealo/Repos/jsoncdc/target/debug/build/jsoncdc-52ee129ced527b62/out" "-L" "/usr/local/Cellar/rust/1.9.0/lib/rustlib/x86_64-apple-darwin/lib" "-Wl,-force_load,/Users/jmealo/Repos/jsoncdc/target/debug/build/jsoncdc-52ee129ced527b62/out/libmagic.a" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.WQQMqXOdyJ9B/librpgffi-f072e56fce3c71d0.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.WQQMqXOdyJ9B/liblibc-87e81dcd3af1ebe2.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.WQQMqXOdyJ9B/libstd-d16b8f0e.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.WQQMqXOdyJ9B/libcollections-d16b8f0e.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.WQQMqXOdyJ9B/librustc_unicode-d16b8f0e.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.WQQMqXOdyJ9B/librand-d16b8f0e.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.WQQMqXOdyJ9B/liballoc-d16b8f0e.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.WQQMqXOdyJ9B/liballoc_system-d16b8f0e.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.WQQMqXOdyJ9B/liblibc-d16b8f0e.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.WQQMqXOdyJ9B/libcore-d16b8f0e.rlib" "-l" "System" "-l" "pthread" "-l" "c" "-l" "m" "-dynamiclib" "-Wl,-dylib" "-l" "compiler-rt"
note: Undefined symbols for architecture x86_64:
  "_row_to_json", referenced from:
      jsoncdc::row_to_json::h2296755287a2ad1b in jsoncdc.0.o
  "_DirectFunctionCall1Coll", referenced from:
      jsoncdc::append_tuple_buf_as_json::hebe35695051cfb66 in jsoncdc.0.o
  "_text_to_cstring", referenced from:
      jsoncdc::append_tuple_buf_as_json::hebe35695051cfb66 in jsoncdc.0.o
  "_escape_json", referenced from:
      _$LT$$BP$mut$u20$pg..Struct_StringInfoData$u20$as$u20$PGAppend$LT$$RF$$u27$a$u20$str$GT$$GT$::add_json::h2a7eecc3baa27181 in jsoncdc.0.o
      _$LT$$BP$mut$u20$pg..Struct_StringInfoData$u20$as$u20$PGAppend$LT$$BP$mut$u20$i8$GT$$GT$::add_json::h100b94d84def4921 in jsoncdc.0.o
  "_get_rel_name", referenced from:
      jsoncdc::append_schema::hebae2773e8032ce4 in jsoncdc.0.o
      jsoncdc::append_change::h7d13bfcd483705d1 in jsoncdc.0.o
  "_get_rel_namespace", referenced from:
      jsoncdc::append_schema::hebae2773e8032ce4 in jsoncdc.0.o
      jsoncdc::append_change::h7d13bfcd483705d1 in jsoncdc.0.o
  "_heap_copy_tuple_as_datum", referenced from:
      jsoncdc::append_tuple_buf_as_json::hebe35695051cfb66 in jsoncdc.0.o
  "_appendStringInfo", referenced from:
      jsoncdc::begin::h1292945af7e1dc85 in jsoncdc.0.o
      jsoncdc::commit::hc1327e5350b56f75 in jsoncdc.0.o
  "_palloc0", referenced from:
      jsoncdc::startup::hf0c8b1735931413f in jsoncdc.0.o
  "_get_attname", referenced from:
      jsoncdc::append_schema::hebae2773e8032ce4 in jsoncdc.0.o
  "_get_namespace_name", referenced from:
      jsoncdc::append_schema::hebae2773e8032ce4 in jsoncdc.0.o
      jsoncdc::append_change::h7d13bfcd483705d1 in jsoncdc.0.o
  "_quote_qualified_identifier", referenced from:
      jsoncdc::append_schema::hebae2773e8032ce4 in jsoncdc.0.o
      jsoncdc::append_change::h7d13bfcd483705d1 in jsoncdc.0.o
  "_get_atttype", referenced from:
      jsoncdc::append_schema::hebae2773e8032ce4 in jsoncdc.0.o
  "_appendStringInfoString", referenced from:
      _$LT$$BP$mut$u20$pg..Struct_StringInfoData$u20$as$u20$PGAppend$LT$$RF$$u27$a$u20$str$GT$$GT$::add_str::he8115336e7f9584e in jsoncdc.0.o
      _$LT$$BP$mut$u20$pg..Struct_StringInfoData$u20$as$u20$PGAppend$LT$$BP$mut$u20$i8$GT$$GT$::add_str::h3cd933c54dd0dda1 in jsoncdc.0.o
      jsoncdc::append_tuple_buf_as_json::hebe35695051cfb66 in jsoncdc.0.o
  "_timestamptz_to_str", referenced from:
      jsoncdc::commit::hc1327e5350b56f75 in jsoncdc.0.o
  "_format_type_be", referenced from:
      jsoncdc::append_schema::hebae2773e8032ce4 in jsoncdc.0.o
  "_pfree", referenced from:
      jsoncdc::shutdown::hd8b78210e92652ee in jsoncdc.0.o
  "_OutputPluginWrite", referenced from:
      jsoncdc::begin::h1292945af7e1dc85 in jsoncdc.0.o
      jsoncdc::change::h0c3945e4505312a9 in jsoncdc.0.o
      jsoncdc::commit::hc1327e5350b56f75 in jsoncdc.0.o
  "_OutputPluginPrepareWrite", referenced from:
      jsoncdc::begin::h1292945af7e1dc85 in jsoncdc.0.o
      jsoncdc::change::h0c3945e4505312a9 in jsoncdc.0.o
      jsoncdc::commit::hc1327e5350b56f75 in jsoncdc.0.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: aborting due to previous error
error: Could not compile `jsoncdc`.
```

```
jmealo$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading gcc v0.3.32
   Compiling libc v0.2.14
   Compiling gcc v0.3.32
   Compiling rpgffi v0.0.1
   Compiling jsoncdc v0.0.9 (file:///Users/jmealo/Repos/jsoncdc)
error: linking with `cc` failed: exit code: 1
note: "cc" "-m64" "-L" "/usr/local/Cellar/rust/1.9.0/lib/rustlib/x86_64-apple-darwin/lib" "/Users/jmealo/Repos/jsoncdc/target/debug/jsoncdc.0.o" "-o" "/Users/jmealo/Repos/jsoncdc/target/debug/libjsoncdc.dylib" "/Users/jmealo/Repos/jsoncdc/target/debug/jsoncdc.metadata.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/jmealo/Repos/jsoncdc/target/debug" "-L" "/Users/jmealo/Repos/jsoncdc/target/debug/deps" "-L" "/Users/jmealo/Repos/jsoncdc/target/debug/build/jsoncdc-52ee129ced527b62/out" "-L" "/usr/local/Cellar/rust/1.9.0/lib/rustlib/x86_64-apple-darwin/lib" "-Wl,-force_load,/Users/jmealo/Repos/jsoncdc/target/debug/build/jsoncdc-52ee129ced527b62/out/libmagic.a" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.xUPwBPCZrvsa/librpgffi-c400a8909370060d.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.xUPwBPCZrvsa/liblibc-87e81dcd3af1ebe2.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.xUPwBPCZrvsa/libstd-d16b8f0e.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.xUPwBPCZrvsa/libcollections-d16b8f0e.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.xUPwBPCZrvsa/librustc_unicode-d16b8f0e.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.xUPwBPCZrvsa/librand-d16b8f0e.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.xUPwBPCZrvsa/liballoc-d16b8f0e.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.xUPwBPCZrvsa/liballoc_system-d16b8f0e.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.xUPwBPCZrvsa/liblibc-d16b8f0e.rlib" "-Wl,-force_load,/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/rustc.xUPwBPCZrvsa/libcore-d16b8f0e.rlib" "-l" "System" "-l" "pthread" "-l" "c" "-l" "m" "-dynamiclib" "-Wl,-dylib" "-l" "compiler-rt"
note: Undefined symbols for architecture x86_64:
  "_row_to_json", referenced from:
      jsoncdc::row_to_json::hecf40059763b3eb6 in jsoncdc.0.o
  "_DirectFunctionCall1Coll", referenced from:
      jsoncdc::append_tuple_buf_as_json::heec00bd6a17a49e4 in jsoncdc.0.o
  "_text_to_cstring", referenced from:
      jsoncdc::append_tuple_buf_as_json::heec00bd6a17a49e4 in jsoncdc.0.o
  "_escape_json", referenced from:
      _$LT$$BP$mut$u20$pg..Struct_StringInfoData$u20$as$u20$PGAppend$LT$$RF$$u27$a$u20$str$GT$$GT$::add_json::h75f47cea667e8568 in jsoncdc.0.o
      _$LT$$BP$mut$u20$pg..Struct_StringInfoData$u20$as$u20$PGAppend$LT$$BP$mut$u20$i8$GT$$GT$::add_json::hd52f4e541aca90ef in jsoncdc.0.o
  "_get_rel_name", referenced from:
      jsoncdc::append_schema::h0d43a2fd2af47b7b in jsoncdc.0.o
      jsoncdc::append_change::h15a8c11535c4a3c4 in jsoncdc.0.o
  "_get_rel_namespace", referenced from:
      jsoncdc::append_schema::h0d43a2fd2af47b7b in jsoncdc.0.o
      jsoncdc::append_change::h15a8c11535c4a3c4 in jsoncdc.0.o
  "_heap_copy_tuple_as_datum", referenced from:
      jsoncdc::append_tuple_buf_as_json::heec00bd6a17a49e4 in jsoncdc.0.o
  "_appendStringInfo", referenced from:
      jsoncdc::begin::h66fa6de96c6effa7 in jsoncdc.0.o
      jsoncdc::commit::he3b34af791c3e211 in jsoncdc.0.o
  "_palloc0", referenced from:
      jsoncdc::startup::h0d8c799bfa140d14 in jsoncdc.0.o
  "_get_attname", referenced from:
      jsoncdc::append_schema::h0d43a2fd2af47b7b in jsoncdc.0.o
  "_get_namespace_name", referenced from:
      jsoncdc::append_schema::h0d43a2fd2af47b7b in jsoncdc.0.o
      jsoncdc::append_change::h15a8c11535c4a3c4 in jsoncdc.0.o
  "_quote_qualified_identifier", referenced from:
      jsoncdc::append_schema::h0d43a2fd2af47b7b in jsoncdc.0.o
      jsoncdc::append_change::h15a8c11535c4a3c4 in jsoncdc.0.o
  "_get_atttype", referenced from:
      jsoncdc::append_schema::h0d43a2fd2af47b7b in jsoncdc.0.o
  "_appendStringInfoString", referenced from:
      _$LT$$BP$mut$u20$pg..Struct_StringInfoData$u20$as$u20$PGAppend$LT$$RF$$u27$a$u20$str$GT$$GT$::add_str::h40b69eedcefb12fd in jsoncdc.0.o
      _$LT$$BP$mut$u20$pg..Struct_StringInfoData$u20$as$u20$PGAppend$LT$$BP$mut$u20$i8$GT$$GT$::add_str::h263ede09ff21cae7 in jsoncdc.0.o
      jsoncdc::append_tuple_buf_as_json::heec00bd6a17a49e4 in jsoncdc.0.o
  "_timestamptz_to_str", referenced from:
      jsoncdc::commit::he3b34af791c3e211 in jsoncdc.0.o
  "_format_type_be", referenced from:
      jsoncdc::append_schema::h0d43a2fd2af47b7b in jsoncdc.0.o
  "_pfree", referenced from:
      jsoncdc::shutdown::h931a146f570fb6e4 in jsoncdc.0.o
  "_OutputPluginWrite", referenced from:
      jsoncdc::begin::h66fa6de96c6effa7 in jsoncdc.0.o
      jsoncdc::change::ha8fc814bcea0a0f8 in jsoncdc.0.o
      jsoncdc::commit::he3b34af791c3e211 in jsoncdc.0.o
  "_OutputPluginPrepareWrite", referenced from:
      jsoncdc::begin::h66fa6de96c6effa7 in jsoncdc.0.o
      jsoncdc::change::ha8fc814bcea0a0f8 in jsoncdc.0.o
      jsoncdc::commit::he3b34af791c3e211 in jsoncdc.0.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: aborting due to previous error
error: Could not compile `jsoncdc`.

To learn more, run the command again with --verbose.
```

**Comment by jmealo** [comment]
pgxn install works on OSX and not on Ubuntu 16.04 (https://github.com/posix4e/jsoncdc/issues/66):

```
Jeffreys-MacBook-Pro:jsoncdc jmealo$ pgxn install jsoncdc --unstable
INFO: best version: jsoncdc 0.0.9
INFO: saving /var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/tmptpjkSR/jsoncdc-0.0.9.zip
INFO: unpacking: /var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/tmptpjkSR/jsoncdc-0.0.9.zip
INFO: building extension
++ pg_config --version
++ cut '-d ' -f2
++ tr -d .
++ cut -c-2
+ pg_short_version=pg95
+ echo pg95
cargo rustc --release -- -C link-args='-Wl,-undefined,dynamic_lookup'
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling gcc v0.3.32
   Compiling libc v0.2.14
   Compiling rpgffi v0.0.1
   Compiling jsoncdc v0.0.9 (file:///private/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/tmptpjkSR/jsoncdc-0.0.9)
cp target/release/libjsoncdc.* jsoncdc.so
cp sql/jsoncdc.sql sql/jsoncdc--0.0.9.sql
INFO: installing extension
++ pg_config --version
++ cut '-d ' -f2
++ tr -d .
++ cut -c-2
+ pg_short_version=pg95
+ echo pg95
cargo rustc --release -- -C link-args='-Wl,-undefined,dynamic_lookup'
   Compiling jsoncdc v0.0.9 (file:///private/var/folders/jk/2tghtl1579l2pvbx68wt91vm0000gn/T/tmptpjkSR/jsoncdc-0.0.9)
cp target/release/libjsoncdc.* jsoncdc.so
/bin/sh /usr/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/share/postgresql/extension'
/bin/sh /usr/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/share/postgresql/extension'
/bin/sh /usr/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/lib/postgresql'
/bin/sh /usr/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/Cellar/postgresql/9.5.3/share/doc/postgresql/extension'
/usr/bin/install -c -m 644 .//jsoncdc.control '/usr/local/share/postgresql/extension/'
/usr/bin/install -c -m 644 .//sql/jsoncdc.sql .//sql/uninstall_jsoncdc.sql  '/usr/local/share/postgresql/extension/'
/usr/bin/install -c -m 755  jsoncdc.so '/usr/local/lib/postgresql/'
/usr/bin/install -c -m 644 .//doc/jsoncdc.md '/usr/local/Cellar/postgresql/9.5.3/share/doc/postgresql/extension/'
```

**Comment by solidsnack** [comment]
@jmealo When we link `jsoncdc`, some symbols must remain unresolved -- they will only be available when the plugin is loaded in the server. On OSX, this goes against the default behaviour of the toolchain, so `cargo build` does not work in a naive way. In the `Makefile`, we use `cargo rustc` and pass some options.

**Comment by solidsnack** [comment]
@jmealo Thank you for your PR. We look forward to merging this today.
